name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
          check-latest: true

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build binaries
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          # Create directory for binaries
          mkdir -p dist

          # Build for Linux (amd64)
          GOOS=linux GOARCH=amd64 go build -o dist/github-mcp-go_${VERSION}_linux_amd64 .
          
          # Build for Linux (arm64)
          GOOS=linux GOARCH=arm64 go build -o dist/github-mcp-go_${VERSION}_linux_arm64 .
          
          # Build for macOS (amd64)
          GOOS=darwin GOARCH=amd64 go build -o dist/github-mcp-go_${VERSION}_darwin_amd64 .
          
          # Build for macOS (arm64)
          GOOS=darwin GOARCH=arm64 go build -o dist/github-mcp-go_${VERSION}_darwin_arm64 .
          
          # Build for Windows (amd64)
          GOOS=windows GOARCH=amd64 go build -o dist/github-mcp-go_${VERSION}_windows_amd64.exe .
          
          # Create checksums
          cd dist
          sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/github-mcp-go_${{ steps.get_version.outputs.VERSION }}_linux_amd64
            dist/github-mcp-go_${{ steps.get_version.outputs.VERSION }}_linux_arm64
            dist/github-mcp-go_${{ steps.get_version.outputs.VERSION }}_darwin_amd64
            dist/github-mcp-go_${{ steps.get_version.outputs.VERSION }}_darwin_arm64
            dist/github-mcp-go_${{ steps.get_version.outputs.VERSION }}_windows_amd64.exe
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
